# Homework 2: Naive Bayes Email Spam Filter

In this homework, we will learn how to implement the Naive Bayes classifier in order to create a simple email spam filter. This spam filter will be trained by test_emails, which will be given by a vector of tuples (emails, spam/nospam). For each tuple the first entry is a string ("email"), and the second entry is 0 or 1, depending whether the email contains spam words.

In [1]:
dictionary = ['hello', 'students', 'please', 'learn', 'for', 'the', 'exam', 'buy', 'drugs', 'today', 'sun', 'is', 'shining', 'in', 'nagoya', 'lets', 'sell', 'how', 'are', 'you', 'today?', 'do', 'your', 'homework', 'want', 'free', 'solutions?', 'hey', 'always', 'ask', 'questions', 'if','have', 'any', 'math', 'not', 'good', 'submit', 'pay'] 

test_emails=[
             ["hello students, please learn for the exam", 0],
             ["hello students, please buy drugs", 1],    
             ["hello, today the sun is shining in nagoya", 0],
             ["lets sell drugs in nagoya", 1],
             ["today learn drugs", 1],
             ["how are you today?", 0],
             ["hello students, please do your homework", 0],
             ["hello, do you want free homework solutions?", 1],
             ["hey students, please always ask questions if you have any", 0],
             ["math is not good", 1],
             ["math is good", 0],
             ["please submit your homework", 0],
             ["please buy questions", 1],
             ["please pay for the exam", 1]          
             ]

The feature space for our spam filter will be $\mathcal{X}=\{0,1\}^d$, where $d$ denotes the number of words in the dictionary. For a feature (email) $x \in \mathcal{X}$ the entry $x_i$ for $i=1,\dots,d$ is $1$ if the $i$-th word of the dictionary is contained in the email and $0$ otherwise.  

$$P(y)\cdot\prod_d P(x_i=k|y)=\frac{N(y)}N\cdot\prod_d\frac{\lambda^k e^{-\lambda}}{k!}$$

In [3]:
import numpy as np

class spamFilter:
    _dic={}
    _total_mail=np.array([0,0]) 
    
    def __init__(self,emails=[],labels=[]):
        self.train(emails,labels)

    def train(self,emails,labels):
        if type(emails)==str:
            emails=[emails.split()]
            labels=[labels]
        elif type(emails)==list or type(emails)==tuple:
            assert len(emails)==len(labels)
            emails=map(str.split,emails)
        else:
            raise Exception("single or 1d string iterable is expected.")



        for email,label in zip(emails,labels):
            assert label in [0,1]
            self._total_mail+=np.array([1,label])
            for word in email:
                try:
                    self._dic[word]+=np.array([1,label])
                except KeyError:
                    self._dic[word]=np.array([1,label])
    
    def _poission(self,k,l):
        return np.exp(-l)*np.power(l,k)/np.math.factorial(k)
    
    def predict(self,emails,smoothing='laplace',threshold=False):
        assert smoothing in [None,"laplace"]
        if type(emails)==str:
            emails=[emails.split()]
        elif type(emails)==list or type(emails)==tuple:
            emails=map(str.split,emails)
        else:
            raise Exception("single or 1d string iterable is expected.")
        if smoothing==None:
            assert self._total_mail[0]!=0
        if threshold=='auto':
            threshold=self.predict("",smoothing=smoothing)
        if threshold!=False:
            assert 1>float(threshold)>0



        smooth = 0 if smoothing==None else 1
        y=[]
        for email in emails:
            try:
                sum=[
                    self._total_mail[1]+smooth,
                    self._total_mail[0]-self._total_mail[1]+smooth
                    ]
            except ZeroDivisionError:
                y.append(0. if _total_mail[1]==0 else 1.)
                continue

            mailDic={}
            for word in email:
                mailDic[word]= mailDic[word]+1 if word in mailDic else 1
            
            for word in self._dic:
                cnt = mailDic[word] if word in mailDic else 0
                sum[0]*=self._poission(cnt,(self._dic[word][1]+smooth)/(self._total_mail[1]+2*smooth))
                sum[1]*=self._poission(cnt,(self._dic[word][0]-self._dic[word][1]+smooth)/(self._total_mail[0]-self._total_mail[1]+2*smooth))
            y.append(sum[0]/(sum[0]+sum[1]) if sum[0]+sum[1]!=0 else -1)
        if threshold!=False:
            y=[1 if i>threshold else 0 for i in y]
        return np.array(y)
        

In [4]:
X=[]
Y=[]
for x,y in test_emails:
    X.append(x)
    Y.append(y)

In [5]:
model=spamFilter(X,Y)

In [6]:
model.predict(X,threshold='auto')-Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
model.predict(X,threshold='auto',smoothing=None)-Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
model.predict(X)

array([0.35066672, 0.90672287, 0.25235084, 0.97984022, 0.92395973,
       0.20200731, 0.15255224, 0.91526016, 0.01249901, 0.80199232,
       0.66943837, 0.2126112 , 0.87938083, 0.76416469])

In [9]:
model.predict(X,smoothing=None)

array([0.20685019, 1.        , 0.        , 1.        , 1.        ,
       0.        , 0.        , 1.        , 0.        , 1.        ,
       0.67599446, 0.        , 1.        , 1.        ])

In [10]:
model.predict("new")

array([0.7523362])

In [11]:
model.train(["new1","new2"],[0,1])

In [12]:
model.predict(["new1","new2","new3"])

array([0.57611688, 0.8446376 , 0.73105858])

In [13]:
model.predict("math == drugs")

array([0.91577619])

# **Exercise 1**
Implement a function which creates a feature vector out of an email and a function which creates a training set out of test emails. 

You would need to figure out whether a sentence contains a word, and there are functions in Python that could determine whether a string contains another string. You can consult documentation (and Google) to find out.

In [12]:
import numpy as np
def email_to_feature(dict, email):
  raise NotImplementedError

def emails_to_test_samples(dict, test_emails):
  raise NotImplementedError

 **Recall from Lecture 6:**

Given a training set  $\mathcal{T} = \left( (x^{(1)}, y^{(1)}) , \dots, (x^{(n)}, y^{(n)})   \right)$ we calculate for $i=1,\dots,d$ the following numbers
\begin{align*}
\phi_{i\mid y=1} &= \frac{1+\sum_{j=1}^n I(x^{(j)}_i = 1  \,\wedge \, y^{(j)}=1 ) }{2+\sum_{j=1}^n I(y^{(j)}=1)}\,,\\
	\phi_{i\mid y=0} &= \frac{1+\sum_{j=1}^n I(x^{(j)}_i = 1  \,\wedge \, y^{(j)}=0 )}{2+\sum_{j=1}^n I(y^{(j)}=0)}\,,\\
		\phi_{y=1} &= \frac{1+\sum_{j=1}^n I(y^{(j)} = 1)}{2+n} \,.
\end{align*}
Here $I$ denoted the indicator function. We used the laplace smoothing (thats why we have the $1+$ and $2+$) in order to make sure that we will not assume probability $0$ for unknown words.

Now assume we get a new feature (i.e. someone sends us an email) $x \in \{0,1\}^d$. Then we can calculate for each word $i=1,\dots,d$ the probabilities
\begin{align*}
P(x_i = 1 \mid y=1) &= \phi_{i\mid y=1}\,,\qquad &&P(x_i = 1 \mid y=0) = \phi_{i\mid y=0} \,,\\
P(x_i = 0 \mid y=1) &= 1- \phi_{i\mid y=1}\,,\qquad &&P(x_i = 0 \mid y=0) = 1-\phi_{i\mid y=0} \,. \\
\end{align*}

By the Naive Bayes assumption we have for $x \in \{0,1\}^d$
\begin{align*}
P(x \mid y)  = \prod_{i=1}^d P(x_j \mid y)\,.
\end{align*}
The probability of the new email being spam is then
\begin{align*}
P(y=1 \mid x) &= \frac{ P(x \mid y=1) P(y=1)}{P(x)}\\
&= \frac{\prod_{i=1}^d P(x_i \mid y = 1) \cdot \phi_{y=1}}{\prod_{i=1}^d P(x_i \mid y = 1) \cdot \phi_{y=1} + \prod_{i=1}^d P(x_i \mid y = 0) (1-\phi_{y=1})}\,.
\end{align*}


# **Exercise 2:** 
Use the above explanation of the Naive Bayes Spam filter and implement a function which gives the probability of an email being spam given the trainings email above. 


In [13]:
# You can implement the above algorithm in any way you want.
# One possible way:
# - Calculate the phis here
# - Write functions for the probability P(x|y) depending on these phis
# - Use this function in the function spam_percentage 

def spam_percentage(email):

  return NotImplementedError

Test your spam filter with the following email.


In [14]:
email="the sun is shining. buy drugs now"
print(SpamPercentage(email))

NameError: name 'SpamPercentage' is not defined


# **Exercise 3**
Extend your spamfilter by creating a dynamical dictionary. Instead of starting with a fixed dictionary, you should now create a dictionary out of a list of emails. 

Write a function `create_dictionary(emails)` which returns a dictionary created from a list of emails (Give as an array of arrays `[text, spam\nospam]`). Make sure that you do not include words more than once into the dictionary.
To implement this function you should look up the function `split()` for a string in Python. To take care of the symbols "." and "," you can use the `replace()` function of a string.